### ISSUE TITLE
Error when loading minecraft-api

### ISSUE THREAD

**Issue by clottedcode** [OvercastNetwork/minecraft-api#2]
I put the minecraft-api jar file into my /plugins folder but the flaw
`Invalid plugin.yml` shows up.
Can you help me?

**Comment by jedediah** [comment]
It's not a plugin, it's a library, only useful to developers.

**Comment by clottedcode** [comment]
But how should you use that library?

**Comment by jedediah** [comment]
It's part of SportBukkit and the OCN fork of BungeeCord

**Comment by clottedcode** [comment]
Thanks very much, but how do I set that BungeeCord OCN fork up? Can you help me with that?

**Comment by TheMolkaPL** [comment]
@vliegendevogel You have to compile this: https://github.com/OvercastNetwork/BungeeCord
